# Build the Flatpak

include: 'https://gitlab.gnome.org/GNOME/citemplates/-/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
  BUNDLE: "${APP_ID}.flatpak"
  # We currently don't have any tests, remove "RUN_TESTS" to run tests
  RUN_TESTS: "0"

build@x86_64:
  extends:
    - .flatpak@x86_64
  stage: build

build@aarch64:
  extends:
    - .flatpak@aarch64
  stage: build
